### ISSUE TITLE
PUT-Method zum rejecten von Matches

### ISSUE THREAD

**Issue by LinusTU** [ExtremeEnvironment/disaster-service#29]
disasterservice/api/actions/reject/{id}

**Comment by xetys** [comment]
bitte näher auf die methoden GET/POST/PUT/DELETE eingehen (methode -> bedeutung / überhaupt definiert?)

**Comment by zergar** [comment]
URI changed: 
PUT disasterservice/api/actions/{id}/rejectMatch
