### ISSUE TITLE
GET-Method, die alle action Knowledge zu einer Katastrophe wieder gibt

### ISSUE THREAD

**Issue by LinusTU** [ExtremeEnvironment/disaster-service#30]
disasterservice/api/actions/knowledge/{id}

**Comment by xetys** [comment]
bitte näher auf die methoden GET/POST/PUT/DELETE eingehen (methode -> bedeutung / überhaupt definiert?)

**Comment by tuberinfo** [comment]
/actions/{id}/knowledge
