### ISSUE TITLE
GET-Method, die alle Actions mit Type Knowledge und Seek zu einer bestimmten Katastrophe zurück gibt

### ISSUE THREAD

**Issue by LinusTU** [ExtremeEnvironment/disaster-service#31]
disasterservice/api/actions/heatmap/{id}

**Comment by xetys** [comment]
bitte näher auf die methoden GET/POST/PUT/DELETE eingehen (methode -> bedeutung / überhaupt definiert?)

**Comment by LinusTU** [comment]
vlt. war Schnittstelle eine ungenau Wortwahl, habe es korrigiert. Gemeint ist eigentlich nur, dass die jeweiligen Methoden in den schon bestehenden Ressourcen hinzugefügt werden sollen.

**Comment by zergar** [comment]
URI changed:
disasterservice/api/actions/{id}/heatmap

**Comment by zergar** [comment]
URI changed to:
GET disasterservice/api/disasters/{id}/heatmap
